export const state = {
  COMPS_DATA: [],
  ROSTER: [],
  MEMBERS: [],
  ROLES: {},
  ROLE_LABEL: {},
  ROLE_FULL: {},
  S_TIER: [],
  GLOBAL_NOTES: [],
  AGENT_FR: {},
  PLAYER_STATS: {},
  currentPage: 'home',
  currentProfile: null,
  currentMapIdx: 0,
  LINEUPS: {},
  META: {},
  currentCompIdx: {},
};
