export const state = {
  COMPS_DATA: [],
  ROSTER: [],
  ROLES: {},
  ROLE_LABEL: {},
  ROLE_FULL: {},
  S_TIER: [],
  GLOBAL_NOTES: [],
  AGENT_FR: {},
  FAVS: [],
  PLAYER_STATS: {},
  currentAgentFilter: 'all',
  currentPage: 'home',
  compareSelections: [],
  builderSlots: [null,null,null,null,null],
  builderFocusSlot: 0,
  builderMapIdx: null,
  currentProfile: null,
  currentMapIdx: 0,
  LINEUPS: {},
  CALLOUTS: {},
  META: {},
  currentCompIdx: {},
};
