import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { updateScriptDownload } from '../js/downloads.mjs';
const label = { textContent:'' };
const button = { hidden:true, querySelector:() => label };
updateScriptDownload(button);
assert.equal(button.hidden, false);
assert.equal(label.textContent, 'Télécharger le script');
updateScriptDownload(button, true, '4.17.12');
assert.equal(label.textContent, 'Mettre à jour le script');
assert.ok(button.title.includes('4.17.12'));
updateScriptDownload(button);
assert.equal(label.textContent, 'Télécharger le script');
assert.doesNotThrow(() => updateScriptDownload(null));
const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8');
assert.ok(html.includes('data-download-label>Télécharger le script'));
assert.ok(html.includes('href="https://github.com/liam-thorel/OLYVALO/releases/latest" target="_blank"'));
assert.ok(!html.includes('OLYCITY-Overlay-Setup.exe'));
console.log('downloads: liens séparés et script accessible avec ou sans membres connectés');
